export const workerTableHeaders = [
  'No',
  'Категория',
  'Фильтр',
  'Теги',
  'Дата и время',
  'Адрес',
  'Организатор',
  'Название',
  'Цена от',
  'Цена для детей',
  'Цена для взрослых',
  'Возрастные ограничеия',
  'Тип кнопки',
  'Постоянство',
  'Описание',
  'Что ты можешь сделать?',
  'Инфраструктура',
  'Инструкция',
  'Дополнительная информация',
  'Галерея',
  'Дата добавления',
];

export const workers = [
  {
    id: '1',
    category: 'a',
    filter: 'b',
    tags: 'c',
    dateAndTime: 'd',
    address: 'e',
    organizer: 'f',
    nameOfLeisure: 'g',
    price: {
      from: 'h',
    },
    ageRestrictions: 'i',
    buttonType: 'k',
    permanentEvent: false,
    description: 'r',
    whatCanYouDo: 's',
    infrastructure: 't',
    instruction: 'u',
    additionalInformation: 'w',
    gallery: ['img1', 'img2', 'img3'],
    dateAdded: 'x',
  },
];
