export const workerTableHeaders = [
  'No',
  'Категория',
  'Фильтр',
  'Теги',
  'Организатор',
  'Галерея',
  'Адрес',
  'Цена для детей',
  'Цена от',
  'Цена для взрослых',
  'Постоянство',
  'Дата и время',
  'Название',
  'Возрастные ограничеия',
  'Тип кнопки',
  'Описание',
  'Что ты можешь сделать?',
  'Инфраструктура',
  'Инструкция',
  'Дополнительная информация',
  'Дата добавления',
];

export const workers = [
  {
    id: '1',
    category: 'a',
    filter: 'b',
    tags: ['тег1', 'тег2', 'тег3', 'тег4'],
    gallery: ['img1', 'img2', 'img3'],
    address: 'e',
    dateAndTime: ['дата 1', 'дата 1'],
    price: {
      from: 1200,
      children: { weekdays: 1200, weekend: 1300 },
      adults: { weekdays: 1400, weekend: 1600 },
    },
    nameOfLeisure: 'название',
    ageRestrictions: 'возраст',
    buttonType: 'тип кнопки',
    permanentEvent: true,
    description: 'описание',
    whatCanYouDo: 'что ты можешь сделать',
    infrastructure: 'инфр',
    instruction: 'инстр',
    organizer: 'орг',
    additionalInformation: 'доп',
    dateAdded: 'дат доб',
  },
  {
    id: '2',
    category: 'a',
    filter: 'b',
    tags: ['тег1', 'тег2', 'тег3', 'тег4'],
    gallery: ['img1', 'img2', 'img3'],
    address: 'e',
    dateAndTime: ['дата 1', 'дата 1'],
    price: {
      from: 1200,
      children: { weekdays: 1200, weekend: 1300 },
      adults: { weekdays: 1400, weekend: 1600 },
    },
    nameOfLeisure: 'название',
    ageRestrictions: 'возраст',
    buttonType: 'тип кнопки',
    permanentEvent: true,
    description: 'описание',
    whatCanYouDo: 'что ты можешь сделать',
    infrastructure: 'инфр',
    instruction: 'инстр',
    organizer: 'орг',
    additionalInformation: 'доп',
    dateAdded: 'дат доб',
  },
];
